"""empty message

Revision ID: 9213dc31579b
Revises: 
Create Date: 2022-07-06 13:15:13.467189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9213dc31579b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.LargeBinary(), nullable=True),
    sa.Column('account', sa.LargeBinary(), nullable=True),
    sa.Column('correspondent_account', sa.LargeBinary(), nullable=True),
    sa.Column('bic', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.LargeBinary(), nullable=True),
    sa.Column('name_short', sa.LargeBinary(), nullable=True),
    sa.Column('fio_rod', sa.LargeBinary(), nullable=True),
    sa.Column('adress', sa.LargeBinary(), nullable=True),
    sa.Column('ogrn', sa.LargeBinary(), nullable=True),
    sa.Column('inn', sa.LargeBinary(), nullable=True),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_employeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.LargeBinary(), nullable=True),
    sa.Column('fio_short', sa.LargeBinary(), nullable=True),
    sa.Column('pasport', sa.LargeBinary(), nullable=True),
    sa.Column('adress', sa.LargeBinary(), nullable=True),
    sa.Column('phone', sa.LargeBinary(), nullable=True),
    sa.Column('vid_oplati', sa.LargeBinary(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.LargeBinary(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.LargeBinary(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('pdf', sa.LargeBinary(), nullable=True),
    sa.Column('signed', sa.LargeBinary(), nullable=True),
    sa.Column('check', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['self_employeds.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    op.drop_table('service_descriptions')
    op.drop_table('self_employeds')
    op.drop_table('companies')
    op.drop_table('services')
    op.drop_table('banks')
    # ### end Alembic commands ###
